[tool.ruff]
target-version = "py311"
line-length    = 100
lint.select    = ["F","E","W","I","UP","B","C4","YTT"]
lint.ignore    = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**"      = ["S101"]
"migrations/**" = ["E501","B008"]
